name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0

  firebase_core: ^2.24.2

  firebase_auth: ^4.17.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  particles_flutter: ^0.1.4

  user_repository:
    path: packages/user_repository
  food_repository:
    path: packages/food_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1

  
flutter_icons:
  android: true
  ios: false
  image_path: "assets/11.png"

flutter:
  uses-material-design: true
  assets:
    - assets/