name: food_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0

=======
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0

  firebase_core: ^2.24.2

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  user_repository:
    path: packages/user_repository
  food_repository:
    path: packages/food_repository
>>>>>>> 4a70c1a4f5519731fe565bbfe033421f01ddbc21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
